# Generated by Django 6.0.2 on 2026-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_type', models.CharField(choices=[('electricity', 'Electricity'), ('bus_diesel', 'Bus Diesel'), ('canteen_lpg', 'Canteen LPG'), ('waste_landfill', 'Waste (Landfill)')], max_length=100)),
                ('raw_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100, unique=True)),
                ('factor', models.FloatField()),
                ('factor_unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emission_factors',
            },
        ),
        migrations.CreateModel(
            name='HumanPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('student_count', models.IntegerField()),
                ('staff_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'human_population',
                'ordering': ['-date'],
            },
        ),
    ]
