# Generated by Django 4.2.28 on 2026-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='KIT Campus', max_length=200)),
                ('tagline', models.CharField(default='Supporting UN SDG 13: Climate Action', max_length=300)),
                ('address', models.TextField(default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('logo_emoji', models.CharField(default='🏫', max_length=10)),
                ('established_year', models.CharField(blank=True, default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'college_profile',
            },
        ),
    ]
